### PR TITLE
Made previews only load once you first hover over the rewrite rule, cutting down on loading time

### PR DESCRIPTION
**Pull request by jvdwetering**

### CODE REVIEW

**Review by RazinShaikh — APPROVED** [review]
It looks good to me. Shall we merge it?

**Comment by RazinShaikh** [comment]
This PR broke the previews settings. The tooltip shows the preview even when the "Show rewrite previews" is turned off.

**Comment by RazinShaikh** [comment]
We need to use 
```python
if display_setting.previews_show
```
but I think it might need a few more changes because currently the following line overwrites the tooltip_str.
https://github.com/zxcalc/zxlive/blob/40d0ea0db725c584ccd0d8bcd1cbc5a82fe87f4d/zxlive/rewrite_action.py#L156

**Comment by jvdwetering** [comment]
Fixed in f1fb7b247a31a2a8d621f1458faa34ca246ceadc

**Pull request merged**
